"""
Trade Execution Tracker Module

This module provides signal-to-order correlation ID tracking for the trading system.
It tracks the complete lifecycle from signal generation to order execution to position on exchange.

Usage:
    from trade_execution_tracker import TradeExecutionTracker, SignalContext, OrderStatus
    
    tracker = TradeExecutionTracker()
    correlation_id = tracker.create_correlation_id("ETHUSDT")
"""

import logging
import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional

# Configure module logger
logger = logging.getLogger(__name__)


class OrderStatus(Enum):
    """
    Enum representing the various states in the order lifecycle.
    
    States:
        SIGNAL_GENERATED: Signal has been generated by the system
        RISK_APPROVED: Signal has passed risk checks
        LLM_APPROVED: Signal has been approved by LLM guardian
        ORDER_SENT: Order has been sent to exchange
        ORDER_CONFIRMED: Order has been confirmed by exchange
        ORDER_FILLED: Order has been fully filled
        ORDER_FAILED: Order has failed (rejected, cancelled, etc.)
    """
    SIGNAL_GENERATED = "SIGNAL_GENERATED"
    RISK_APPROVED = "RISK_APPROVED"
    LLM_APPROVED = "LLM_APPROVED"
    ORDER_SENT = "ORDER_SENT"
    ORDER_CONFIRMED = "ORDER_CONFIRMED"
    ORDER_FILLED = "ORDER_FILLED"
    ORDER_FAILED = "ORDER_FAILED"


class SignalSource(str, Enum):
    """
    Enum representing the source of a trading signal.
    
    Sources:
        ML: Signal generated by machine learning model
        MANUAL: Signal manually entered by trader
        SCALE_IN: Signal for scaling in to existing position
    """
    ML = "ML"
    MANUAL = "MANUAL"
    SCALE_IN = "SCALE_IN"


class SignalContext:
    """
    Dataclass representing the context of a trading signal.
    
    Attributes:
        signal_id: Unique identifier for the signal
        symbol: Trading symbol (e.g., 'ETHUSDT')
        action: Trading action ('BUY' or 'SELL')
        strength: Signal strength (0.0 to 1.0)
        confidence: Confidence level (0.0 to 1.0)
        price: Signal price
        timestamp: Signal generation timestamp
        source: Source of the signal (ML/MANUAL/SCALE_IN)
        llm_approved: Whether LLM guardian approved the signal
        llm_reason: Reason from LLM guardian approval/rejection
    """
    
    signal_id: str
    symbol: str
    action: str
    strength: float
    confidence: float
    price: float
    timestamp: datetime
    source: SignalSource
    llm_approved: bool
    llm_reason: Optional[str]
    
    def __init__(
        self,
        signal_id: str,
        symbol: str,
        action: str,
        strength: float,
        confidence: float,
        price: float,
        timestamp: Optional[datetime] = None,
        source: SignalSource = SignalSource.ML,
        llm_approved: bool = False,
        llm_reason: Optional[str] = None
    ) -> None:
        self.signal_id = signal_id
        self.symbol = symbol
        self.action = action
        self.signal_id = signal_id
        self.strength = strength
        self.confidence = confidence
        self.price = price
        self.timestamp = timestamp or datetime.now(timezone.utc)
        self.source = source if isinstance(source, SignalSource) else SignalSource(source)
        self.llm_approved = llm_approved
        self.llm_reason = llm_reason
    
    def to_dict(self) -> dict[str, Any]:
        """Convert SignalContext to dictionary."""
        return {
            "signal_id": self.signal_id,
            "symbol": self.symbol,
            "action": self.action,
            "strength": self.strength,
            "confidence": self.confidence,
            "price": self.price,
            "timestamp": self.timestamp.isoformat() if isinstance(self.timestamp, datetime) else self.timestamp,
            "source": self.source.value if isinstance(self.source, SignalSource) else self.source,
            "llm_approved": self.llm_approved,
            "llm_reason": self.llm_reason
        }


class OrderRecord:
    """
    Dataclass representing a trading order record.
    
    Attributes:
        correlation_id: Unique correlation ID linking signal to order
        order_id: Exchange order ID (if available)
        symbol: Trading symbol
        side: Order side ('BUY' or 'SELL')
        quantity: Order quantity
        price: Order price
        status: Current order status
        error_message: Error message if order failed
        timestamps: Dictionary of status -> timestamp mappings
    """
    
    correlation_id: str
    order_id: Optional[str]
    symbol: str
    side: str
    quantity: float
    price: float
    status: OrderStatus
    error_message: Optional[str]
    timestamps: dict[str, str]
    
    def __init__(
        self,
        correlation_id: str,
        symbol: str,
        side: str,
        quantity: float,
        price: float,
        order_id: Optional[str] = None,
        status: OrderStatus = OrderStatus.SIGNAL_GENERATED,
        error_message: Optional[str] = None,
        timestamps: Optional[dict[str, str]] = None
    ) -> None:
        self.correlation_id = correlation_id
        self.order_id = order_id
        self.symbol = symbol
        self.side = side
        self.quantity = quantity
        self.price = price
        self.status = status if isinstance(status, OrderStatus) else OrderStatus(status)
        self.error_message = error_message
        self.timestamps = timestamps or {}
    
    def to_dict(self) -> dict[str, Any]:
        """Convert OrderRecord to dictionary."""
        return {
            "correlation_id": self.correlation_id,
            "order_id": self.order_id,
            "symbol": self.symbol,
            "side": self.side,
            "quantity": self.quantity,
            "price": self.price,
            "status": self.status.value if isinstance(self.status, OrderStatus) else self.status,
            "error_message": self.error_message,
            "timestamps": self.timestamps.copy()
        }


class TradeExecutionTracker:
    """
    Trade Execution Tracker class for signal-to-order correlation tracking.
    
    This class manages the complete lifecycle tracking from signal generation
    through order execution to positions on exchange.
    
    Example:
        tracker = TradeExecutionTracker()
        
        # Create a correlation ID
        correlation_id = tracker.create_correlation_id("ETHUSDT")
        
        # Record a signal
        signal = SignalContext(
            signal_id="sig_123",
            symbol="ETHUSDT",
            action="BUY",
            strength=0.8,
            confidence=0.9,
            price=2500.0,
            source=SignalSource.ML
        )
        corr_id = tracker.record_signal(signal)
        
        # Update order status
        tracker.update_order_status(corr_id, OrderStatus.ORDER_SENT, order_id="ord_456")
        
        # Get active orders
        active_orders = tracker.get_active_orders_summary()
    """
    
    def __init__(self) -> None:
        """Initialize the TradeExecutionTracker."""
        self._signals: dict[str, SignalContext] = {}
        self._orders: dict[str, OrderRecord] = {}
        self._correlation_to_signal: dict[str, str] = {}
        # DB persistence flag
        self._db_persistence_enabled = True
        logger.info("TradeExecutionTracker initialized")
    
    def _persist_to_db(self) -> bool:
        """
        Persist tracker data to database.
        
        Returns:
            True if persistence successful, False otherwise
        """
        if not self._db_persistence_enabled:
            return False
            
        try:
            from state.state_service import state_service
            from state.models import ExecutionTracker
            
            # Calculate totals
            total_signals = len(self._signals)
            total_orders = len(self._orders)
            
            # Count active orders (non-terminal status)
            terminal_statuses = {OrderStatus.ORDER_FILLED.value, OrderStatus.ORDER_FAILED.value}
            active_orders = 0
            for order in self._orders.values():
                status_val = order.status.value if isinstance(order.status, OrderStatus) else order.status
                if status_val not in terminal_statuses:
                    active_orders += 1
            
            # Build status distribution
            status_distribution = {}
            for order in self._orders.values():
                status_val = order.status.value if isinstance(order.status, OrderStatus) else order.status
                status_distribution[status_val] = status_distribution.get(status_val, 0) + 1
            
            # Serialize signals and orders to JSON
            import json
            signals_json = json.dumps({k: v.to_dict() for k, v in self._signals.items()})
            orders_json = json.dumps({k: v.to_dict() for k, v in self._orders.items()})
            
            tracker = ExecutionTracker(
                total_signals=total_signals,
                total_orders=total_orders,
                active_orders=active_orders,
                status_distribution=status_distribution,
                signals_data=signals_json,
                orders_data=orders_json,
            )
            state_service.upsert_execution_tracker(tracker)
            logger.debug(f"Persisted execution tracker to DB: {total_signals} signals, {total_orders} orders")
            return True
        except Exception as e:
            logger.warning(f"Failed to persist execution tracker to DB: {e}")
            return False
    
    def create_correlation_id(self, symbol: str) -> str:
        """
        Generate a unique correlation ID for a trade.
        
        Format: {SYMBOL}_{DATE}_{TIMESTAMP}_{UUID}
        Example: ETHUSDT_20260228_12345678_abc12345
        
        Args:
            symbol: Trading symbol (e.g., 'ETHUSDT')
            
        Returns:
            Unique correlation ID string
        """
        now = datetime.now(timezone.utc)
        date_str = now.strftime("%Y%m%d")
        time_str = now.strftime("%H%M%S")
        unique_id = uuid.uuid4().hex[:8]
        
        correlation_id = f"{symbol.upper()}_{date_str}_{time_str}_{unique_id}"
        logger.debug(f"Created correlation ID: {correlation_id} for symbol: {symbol}")
        return correlation_id
    
    def record_signal(self, signal: SignalContext) -> str:
        """
        Record a trading signal and generate a correlation ID.
        
        Args:
            signal: SignalContext object containing signal details
            
        Returns:
            Generated correlation ID
        """
        correlation_id = self.create_correlation_id(signal.symbol)
        
        # Store signal
        self._signals[correlation_id] = signal
        self._correlation_to_signal[correlation_id] = signal.signal_id
        
        # Create initial order record
        order_record = OrderRecord(
            correlation_id=correlation_id,
            symbol=signal.symbol,
            side=signal.action.upper(),
            quantity=0.0,  # To be filled later
            price=signal.price,
            status=OrderStatus.SIGNAL_GENERATED
        )
        order_record.timestamps[OrderStatus.SIGNAL_GENERATED.value] = (
            datetime.now(timezone.utc).isoformat()
        )
        
        self._orders[correlation_id] = order_record
        
        logger.info(
            f"Recorded signal {signal.signal_id} with correlation ID: {correlation_id}"
        )
        
        return correlation_id
    
    def update_order_status(
        self,
        correlation_id: str,
        status: OrderStatus,
        order_id: Optional[str] = None,
        error: Optional[str] = None
    ) -> bool:
        """
        Update the status of an order.
        
        Args:
            correlation_id: Correlation ID of the order
            status: New OrderStatus
            order_id: Optional exchange order ID
            error: Optional error message if status is ORDER_FAILED
            
        Returns:
            True if update successful, False otherwise
        """
        if correlation_id not in self._orders:
            logger.error(f"Correlation ID not found: {correlation_id}")
            return False
        
        order = self._orders[correlation_id]
        order.status = status
        
        if order_id:
            order.order_id = order_id
        
        if error:
            order.error_message = error
        
        # Record timestamp
        status_key = status.value if isinstance(status, OrderStatus) else status
        order.timestamps[status_key] = datetime.now(timezone.utc).isoformat()
        
        logger.info(
            f"Updated order {correlation_id} status to: {status.value if isinstance(status, OrderStatus) else status}"
        )
        
        # Persist to DB after status update
        self._persist_to_db()
        
        return True
    
    def get_active_orders_summary(self) -> list[dict[str, Any]]:
        """
        Get summary of all active (non-terminal) orders.
        
        Terminal statuses are: ORDER_FILLED, ORDER_FAILED
        
        Returns:
            List of dictionaries containing active order summaries
        """
        terminal_statuses = {OrderStatus.ORDER_FILLED.value, OrderStatus.ORDER_FAILED.value}
        
        active_orders = []
        for correlation_id, order in self._orders.items():
            status_value = order.status.value if isinstance(order.status, OrderStatus) else order.status
            
            if status_value not in terminal_statuses:
                # Get associated signal if available
                signal = self._signals.get(correlation_id)
                
                order_summary = {
                    "correlation_id": correlation_id,
                    "order_id": order.order_id,
                    "symbol": order.symbol,
                    "side": order.side,
                    "quantity": order.quantity,
                    "price": order.price,
                    "status": status_value,
                    "signal_strength": signal.strength if signal else None,
                    "signal_confidence": signal.confidence if signal else None,
                    "signal_source": signal.source.value if signal and hasattr(signal.source, 'value') else None,
                    "llm_approved": signal.llm_approved if signal else None,
                    "timestamps": order.timestamps.copy()
                }
                active_orders.append(order_summary)
        
        logger.debug(f"Retrieved {len(active_orders)} active orders")
        return active_orders
    
    def get_unified_flow(
        self,
        exchange_positions: Optional[list[dict[str, Any]]] = None
    ) -> dict[str, Any]:
        """
        Get complete flow data combining signals, orders, and exchange positions.
        
        This method provides a unified view of the entire trading flow from
        signal generation through order execution to positions on exchange.
        
        Args:
            exchange_positions: Optional list of current exchange positions.
                             Each position should be a dict with keys like:
                             {'symbol': str, 'quantity': float, 'side': str, ...}
            
        Returns:
            Dictionary containing complete flow data including:
            - signals: All recorded signals
            - orders: All order records
            - active_orders: Active orders summary
            - positions: Current exchange positions (if provided)
            - flow_summary: Statistics about the flow
        """
        # Get all signals
        signals_data = {
            corr_id: signal.to_dict() 
            for corr_id, signal in self._signals.items()
        }
        
        # Get all orders
        orders_data = {
            corr_id: order.to_dict() 
            for corr_id, order in self._orders.items()
        }
        
        # Get active orders
        active_orders = self.get_active_orders_summary()
        
        # Calculate flow statistics
        status_counts: dict[str, int] = {}
        for order in self._orders.values():
            status_value = order.status.value if isinstance(order.status, OrderStatus) else order.status
            status_counts[status_value] = status_counts.get(status_value, 0) + 1
        
        # Match positions with orders/signals
        matched_positions = []
        if exchange_positions:
            for position in exchange_positions:
                symbol = position.get("symbol", "")
                # Find corresponding order/signal for this position
                matched_order = None
                for corr_id, order in self._orders.items():
                    if order.symbol.upper() == symbol.upper():
                        if order.status == OrderStatus.ORDER_FILLED:
                            matched_order = order.to_dict()
                            break
                
                position_flow = {
                    "position": position,
                    "matched_order": matched_order,
                    "signal": self._signals.get(matched_order["correlation_id"] if matched_order else "").to_dict() 
                    if matched_order and matched_order.get("correlation_id") in self._signals else None
                }
                matched_positions.append(position_flow)
        
        flow_summary = {
            "total_signals": len(self._signals),
            "total_orders": len(self._orders),
            "active_orders": len(active_orders),
            "status_distribution": status_counts
        }
        
        unified_flow = {
            "signals": signals_data,
            "orders": orders_data,
            "active_orders": active_orders,
            "positions": matched_positions if exchange_positions else [],
            "flow_summary": flow_summary,
            "timestamp": datetime.now(timezone.utc).isoformat()
        }
        
        logger.info(
            f"Unified flow retrieved: {flow_summary['total_signals']} signals, "
            f"{flow_summary['total_orders']} orders, "
            f"{flow_summary['active_orders']} active"
        )
        
        return unified_flow
    
    def get_order_by_correlation(self, correlation_id: str) -> Optional[OrderRecord]:
        """
        Get an order record by its correlation ID.
        
        Args:
            correlation_id: The correlation ID to look up
            
        Returns:
            OrderRecord if found, None otherwise
        """
        return self._orders.get(correlation_id)
    
    def get_signal_by_correlation(self, correlation_id: str) -> Optional[SignalContext]:
        """
        Get a signal context by its correlation ID.
        
        Args:
            correlation_id: The correlation ID to look up
            
        Returns:
            SignalContext if found, None otherwise
        """
        return self._signals.get(correlation_id)
    
    def clear_completed_orders(self, keep_failed: bool = True) -> int:
        """
        Clear completed (terminal) orders from memory.
        
        Args:
            keep_failed: Whether to keep failed orders (default: True)
            
        Returns:
            Number of orders cleared
        """
        terminal_statuses = {OrderStatus.ORDER_FILLED}
        if not keep_failed:
            terminal_statuses.add(OrderStatus.ORDER_FAILED)
        
        orders_to_remove = [
            corr_id for corr_id, order in self._orders.items()
            if order.status in terminal_statuses
        ]
        
        for corr_id in orders_to_remove:
            del self._orders[corr_id]
            if corr_id in self._signals:
                del self._signals[corr_id]
            if corr_id in self._correlation_to_signal:
                del self._correlation_to_signal[corr_id]
        
        logger.info(f"Cleared {len(orders_to_remove)} completed orders")
        return len(orders_to_remove)
